//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimShift.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimShift.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AdaptiveCruiseControl {
            get {
                object obj = ResourceManager.GetObject("AdaptiveCruiseControl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AdaptiveCruiseControlOff {
            get {
                object obj = ResourceManager.GetObject("AdaptiveCruiseControlOff", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AdaptiveCruiseControlOn {
            get {
                object obj = ResourceManager.GetObject("AdaptiveCruiseControlOn", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Alert {
            get {
                return ResourceManager.GetStream("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CruiseControlIcon {
            get {
                object obj = ResourceManager.GetObject("CruiseControlIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CruiseOff {
            get {
                object obj = ResourceManager.GetObject("CruiseOff", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CruiseOn {
            get {
                object obj = ResourceManager.GetObject("CruiseOn", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CuteCar {
            get {
                object obj = ResourceManager.GetObject("CuteCar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0000028A215FDC9F,IJmuiden
        ///00000000001893A0,Pecs
        ///000001D913F65717,Salzburg
        ///000A6C7D46175459,Strasbourg
        ///00BB06C733A2004A,Gdansk
        ///0000000000149823,Koln
        ///0006F4A3A90ED7A0,Bratislava
        ///0000547ADA08D70F,Osnabruck
        ///00000333CD9F84E6,Budapest
        ///0000000069DCE573,Kassel
        ///000000111C4D7549,Munchen
        ///000001D8C85BE9C2,Nurnberg
        ///0000000001F02A80,Lille
        ///000002F505E877A4,Hannover
        ///0000547ADA17E87B,Innsbruck
        ///00004638F3EE339D,Magdeburg
        ///000000000012C313,Kiel
        ///0000000C730CED40,Hamburg
        ///0000000003AB3704,Paris
        ///000000081461CB02 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LUT1_19_cities {
            get {
                return ResourceManager.GetString("LUT1_19_cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prefab.41,-50,65,55,-76
        ///prefab.200,-52,65,54,-76
        ///prefab.67,-60,0,89,-150
        ///prefab.249,-10,0,160,-165
        ///prefab.68,-32,23,42,-48
        ///prefab.261,-42,62,57,-57
        ///prefab.262,-42,62,57,-57
        ///prefab.282,-35,39,84,-50
        ///prefab.283,-35,50,35,-50
        ///prefab.44,-85,62,82,-72
        ///prefab.252,-24,42,27,-23
        ///prefab.330,-23,42,27,-23
        ///prefab.251,-29,9,59,-123
        ///prefab.13,-400,112,146,-475
        ///prefab.203,-85,0,100,-100
        ///prefab.254,-53,42,32,-16
        ///prefab.31,-101,23,31,-60
        ///prefab.34,-113,67,27,-90
        ///prefab.36,-102,67,30,-90
        ///prefab.32,-54,40, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LUT1_19_companies {
            get {
                return ResourceManager.GetString("LUT1_19_companies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idx,prefab descriptor,base-idx,base-pts,,        ///0,prefab.0,1,15,,        ///1,prefab.1,2,,,        ///2,prefab.3,4,,,        ///3,prefab.4,5,,,        ///4,prefab.5,6,,,        ///5,prefab.6,7,,,        ///6,prefab.7,8,8,,        ///7,prefab.8,9,3,,        ///8,prefab.9,A,15,,        ///9,prefab.10,28,13,&lt;check,high-way junction        ///10,prefab.11,4E,,,        ///11,prefab.12,74,8,,        ///12,prefab.13,9A,4,,        ///13,prefab.14,C0,,,        ///14,prefab.15,,,,        ///15,prefab.16,10C,,,        ///16,prefab.17,132,,,        ///17,prefab.18,158,,,        ///18,prefab.19,17E,,,        ///19,prefab.20,29,,,        ///20,prefab.21,4F,,,        ///21,prefab.22,75,,,        ///22,prefab.23,9B,8,,        ///23,prefab.24,C1,8,,        ///24,pr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LUT1_19_prefab {
            get {
                return ResourceManager.GetString("LUT1_19_prefab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LUT1_19_prefab1 {
            get {
                object obj = ResourceManager.GetObject("LUT1_19_prefab1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LUT1_19_roadlook {
            get {
                object obj = ResourceManager.GetObject("LUT1_19_roadlook", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0031F718,road.look0
        ///0051C828,road.look1
        ///00719938,road.look2
        ///00916A48,road.look3
        ///00B13B58,road.look4
        ///00D10C68,road.look5
        ///00F0DD78,road.look6
        ///0110AE88,road.look7
        ///01307F98,road.look8
        ///015050A8,road.look9
        ///050AD088,road.look10
        ///09C3D8E8,road.look11
        ///0E7CE148,road.look12
        ///1335E9A8,road.look13
        ///17EEF208,road.look14
        ///1CA7FA68,road.look15
        ///216102C8,road.look16
        ///261A0B28,road.look17
        ///2AD31388,road.look18
        ///2F8C1BE8,road.look19
        ///09E3A9F8,road.look21
        ///0E9CB258,road.look22
        ///1355BAB8,road.look23
        ///180EC318,road.lo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LUT1_19_roads {
            get {
                return ResourceManager.GetString("LUT1_19_roads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idx,prefab descriptor,base-idx,base-pts,,        ///0,prefab.0,1,15,,        ///1,prefab.1,,,,        ///2,prefab.3,,,,        ///3,prefab.4,,,,        ///4,prefab.5,,,,        ///5,prefab.6,,,,        ///6,prefab.7,8,8,,        ///7,prefab.8,9,3,,        ///8,prefab.9,A,15,,        ///9,prefab.10,28,13,&lt;check,high-way junction        ///10,prefab.11,,,,        ///11,prefab.12,74,8,,        ///12,prefab.13,9A,4,,        ///13,prefab.14,,,,        ///14,prefab.15,,,,        ///15,prefab.16,,,,        ///16,prefab.17,,,,        ///17,prefab.18,,,,        ///18,prefab.19,,,,        ///19,prefab.20,,,,        ///20,prefab.21,,,,        ///21,prefab.22,,,,        ///22,prefab.23,9B,8,,        ///23,prefab.24,C1,8,,        ///24,prefab.25,E7,3,,        ///25,prefab.25 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string prefabs_tmp {
            get {
                return ResourceManager.GetString("prefabs_tmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream tractioncontrol {
            get {
                return ResourceManager.GetStream("tractioncontrol", resourceCulture);
            }
        }
    }
}
